<?php

namespace App\Admin\Controllers;

use App\Admin\Repositories\AdminLog;
use Dcat\Admin\Grid;
use Dcat\Admin\Http\Controllers\AdminController;
use Illuminate\Support\Facades\DB;

class AdminLogController extends AdminController
{
    protected $title = "操作日志";

    protected function grid()
    {
        return Grid::make(AdminLog::make(),function (Grid $grid){
            \App\Common\AdminLog::admin_log(json_encode($_GET),"查看用户操作日志",1,21);
            $grid->model()->orderByDesc("id");
            $grid->column("id","ID");
            $grid->column("admin_id","操作人")->display(function ($v){
               $name = DB::table("admin_users")->where("id",$v)->value("username");
               return $name ?  : "无";
            });
            $grid->column("title","标题");
            $grid->column("content","内容");
            $grid->column("menu_id","菜单模块")->display(function ($v){
                return DB::table("admin_menu")->where("id",$v)->value("title");
            });
            $grid->column("ip","IP")->label();
            $grid->column("created_at","操作时间");

            $grid->disableCreateButton();
            $grid->disableViewButton();
            $grid->disableEditButton();

            $grid->filter(function (Grid\Filter $filter){
               $admin_data = DB::table("admin_users")->pluck("username","id");
               $admin_menu = DB::table("admin_menu")->pluck("title","id");
               $filter->equal('admin_id',"操作人")->select($admin_data);
               $filter->equal("menu_id","菜单")->select($admin_menu);
               $filter->between('created_at',"操作时间")->datetime();
            });
        });
    }

    public function form()
    {

    }

    public function destroy($id)
    {
        return parent::destroy($id); // TODO: Change the autogenerated stub
    }

}
